### ISSUE TITLE
Racer fails to suggest completion after valid newline

### ISSUE THREAD

**Issue by josteink** [racer-rust/emacs-racer#24]
Take the following example from [the book](https://doc.rust-lang.org/book/guessing-game.html):

````rust
use std::io;

fn main() {
    println!("Guess the number!");

    println!("Please input your guess.");

    let mut guess = String::new();
    io::stdin().read_line(&mut guess)
        .ex<TAB>
````

Trying to complete `.ex` on the following newline fails, with "no completion found". If we change the code to have it all on one line, it works:

````rust
use std::io;

fn main() {
    println!("Guess the number!");

    println!("Please input your guess.");

    let mut guess = String::new();
    io::stdin().read_line(&mut guess).ex<TAB>
````

Not sure if this bug is in emacs-racer or racer itself, but I thought this was probably the best place to start :)

**Comment by michaelmera** [comment]
Got here after noticing the same thing. Using racer outside of emacs produce the following error on the example with a newline :

```
PREFIX 9,10,e
error: expected expression, found `<eof>`
END
```

But it seems to work fine without the newline. So I guess it is a problem with racer itself.

**Comment by Wilfred** [comment]
Could you file a bug on racer itself?

**Comment by josteink** [comment]
Not really. Don't think I'm qualified enough in the internals and protocols involved.

**Comment by josteink** [comment]
@michaelmera Anything you could handle?

**Comment by michaelmera** [comment]
I went to the racer repository and it seems like the problem (and several other that are probably related) is already reported but nobody is really working on that.
The reason is that the mid/long-term idea is to use rustc to provide "perfect" completions in racer, instead of the rather limited syntax analysis that is currently implemented. But I have no idea when/if this will be completed.

Unfortunately, I don't have much time available to work on this issue myself. So I just ignored the problem for now. When I really want completion on multiple lines I just temporarily remove the newlines. Less than ideal...
